version: '3' 
services: 
  app: 
    image: nestjs/cli:6.6.0
    ports: 
      - 3000:3000 
    volumes: 
      - ./:/workspace/
    depends_on:
      - db
    links: 
      - db
    command: npm start 
    tty: true
  db: 
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root 
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    ports: 
      - 3306:3306
